### ISSUE TITLE
Adaptar paso 2: contactos

### ISSUE THREAD

**Issue by mariamedp** [11defebrero/motordatos11F#5]
- [x] Parte A: procesamiento contactos
- [x] EDA reporte automático
- [x] Parte B: envío emails de contacto
- [x] Añadir enlaces para contacto en los listados de solicitudes de la web

**Comment by popiula** [comment]
2a revisado y funcionando
Faltaría publicar el formulario y descomentar la línea correspondiente en makefile
(Pero hasta el 11 de noviembre no está previsto que publiquemos el formulario de contacto)

**Comment by popiula** [comment]
Listo el EDA automático

**Comment by popiula** [comment]
Envio de mails también revisado y funcionando
