### ISSUE TITLE
Adaptar paso 3: charlas concertadas

### ISSUE THREAD

**Issue by mariamedp** [11defebrero/motordatos11F#6]
- [x] Paso A: procesamiento charlas concertadas
- [x] Paso B: actualización charlas restantes
- [x] Cambiar listado solicitadas en la web para que se muestren las restantes en vez de todas
- [x] EDA reporte automático

**Comment by popiula** [comment]
Las 3 primeras ya están. He subido los cambios sin hacer pull request 😰

**Comment by popiula** [comment]
Falta añadir los totales en el EDA
