### ISSUE TITLE
Revisar resumen solicitadas

### ISSUE THREAD

**Issue by mariamedp** [11defebrero/motordatos11F#7]
Tres tareas distintas:
- [x] Revisar que el contenido del template [resumen_solicitadas.Rmd](https://github.com/11defebrero/motordatos11F/blob/main/templates/eda/resumen_solicitadas.Rmd) sea el bueno
- [x] Corregir cálculos totales
- [ ] Añadir estadísticas herramientas online?

### Revisar contenido
En el repo original había dos versiones:
- https://github.com/11defebrero/11F2020/blob/master/eda/Resumen_solicitadas_1.Rmd
- https://github.com/11defebrero/11F2020/blob/master/eda/resumen_solicitadas_2.Rmd

Aquí he copiado la versión 2 y añadido las gráficas que había en [otro script](https://github.com/11defebrero/11F2020/blob/master/eda/evolucion_solicitadas.R), pero puede que haya cosas de la v1 que queramos recuperar también.

### Corregir totales
Los cálculos de totales fallaban, de momento los he dejado comentados.

### Estadísticas herramientas online
Este año no hay pregunta de si podría ser online o no, en su lugar se pregunta que herramientas online serían las preferidas. He comentado todas las secciones en las que se hacían cálculos con el campo `videollamada`. El nuevo campo se llama `herramientas_online`, no sé si sería interesante meter estadísticas de esto también.

**Comment by popiula** [comment]
Resuelto lo de los totales.
La plantilla apellidada con _2 es la que usábamos el año pasado junto con el script que has unido.
